strains = [
  ['$100 OG','hybrid'],
  ['9 Pound Hammer','indica'],
  ['Acapulco Gold','sativa'],
  ['ACDC','hybrid'],
  ['Afghani','indica'],
  ['Afgoo','indica'],
  ['AK-47','hybrid'],
  ['Alaskan Thunder Fuck','sativa'],
  ['Allen Wrench','sativa'],
  ['Amnesia','sativa'],
  ['Amnesia Haze','sativa'],
  ['Banana OG','hybrid'],
  ['Bay 11','sativa'],
  ['Berry White','indica'],
  ['Blackberry Kush','indica'],
  ['Blue Cheese','indica'],
  ['Blue Dream','hybrid'],
  ['Blueberry','indica'],
  ['Bubba Kush','indica'],
  ['Bubble Gum','hybrid'],
  ['Cannatonic','hybrid'],
  ['Cheese','hybrid'],
  ['ChemDawg','hybrid'],
  ['Chernobyl','hybrid'],
  ['Cherry Pie','hybrid'],
  ['Chocolope','sativa'],
  ['Cinderella 99','hybrid'],
  ['Cinex','sativa'],
  ['Dancehall','hybrid'],
  ['Death Star','indica'],
  ['Dirty Girl','sativa'],
  ['Double Dream','hybrid'],
  ['Durban Poison','sativa'],
  ['Dutch Treat','hybrid'],
  ['Ewok','hybrid'],
  ['Fruity Pebbles','hybrid'],
  ['G13','indica'],
  ['Gelato','hybrid'],
  ['Ghost Train Haze','sativa'],
  ['God’s Gift','indica'],
  ['Golden Goat','hybrid'],
  ['Granddaddy Purple','indica'],
  ['Grape Ape','indica'],
  ['Grapefruit','sativa'],
  ['Green Crack','sativa'],
  ['Harlequin','sativa'],
  ['Headband','hybrid'],
  ['Herijuana','indica'],
  ['Hindu Kush','indica'],
  ['Ingrid','indica'],
  ['Island Sweet Skunk','sativa'],
  ['Jack Herer','sativa'],
  ['Jean Guy','hybrid'],
  ['Jilly Bean','hybrid'],
  ['Juicy Fruit','hybrid'],
  ['Kali Mist','sativa'],
  ['Kosher Kush','indica'],
  ['LA Confidential','indica'],
  ['Lamb\'s Bread','sativa'],
  ['Larry OG','hybrid'],
  ['Laughing Buddha','sativa'],
  ['Lavender','indica'],
  ['Lemon Haze','sativa'],
  ['Lemonder','hybrid'],
  ['Lodi Dodi','hybrid'],
  ['Mango Kush','hybrid'],
  ['Master Kush','indica'],
  ['Maui Wowie','sativa'],
  ['Mendicino Purps','hybrid'],
  ['Middle Fork','hybrid'],
  ['Northern Lights','indica'],
  ['Obama Kush','indica'],
  ['OG Kush','hybrid'],
  ['Panama red','sativa'],
  ['Permafrost','hybrid'],
  ['Pez','indica'],
  ['Pineapple Chunk','hybrid'],
  ['Pineapple Express','hybrid'],
  ['Pink Kush','hybrid'],
  ['Plushberry','indica'],
  ['Presidential OG','indica'],
  ['Purple Haze','sativa'],
  ['Purple Kush','indica'],
  ['Purple Urkle','indica'],
  ['Rascal OG','hybrid'],
  ['Red Headed Stranger','sativa'],
  ['S.A.G.E.','hybrid'],
  ['Schrom','sativa'],
  ['SFG OG','hybrid'],
  ['Shiatsu Kush','hybrid'],
  ['Skunk #1','hybrid'],
  ['Skywalker','indica'],
  ['Skywalker OG','hybrid'],
  ['Snoop\'s Dream','hybrid'],
  ['Snowcap','hybrid'],
  ['Sour Diesel','sativa'],
  ['Sour OG','hybrid'],
  ['Sour Tsunami','hybrid'],
  ['Space Queen','hybrid'],
  ['Strawberry Cough','sativa'],
  ['Sunset Sherbet','hybrid'],
  ['Super Lemon Haze','sativa'],
  ['Super Silver Haze','sativa'],
  ['Tahoe OG','hybrid'],
  ['Tangerine Dream','hybrid'],
  ['Tangie','sativa'],
  ['Trainwreck','hybrid'],
  ['UK Cheese','hybrid'],
  ['White Fire OG','hybrid'],
  ['White Rhino','indica'],
  ['White Widow','hybrid'],
  ['Willie\'s Wonder','indica'],
  ['XJ-13','hybrid'],
  ['Zkittles','indica']
]


desc "Seed popular strains"
task seed_strain: :environment  do
  strains.each do |pair|
    code = pair[0].gsub(/[\'\s]/, '').underscore

    if Common::Strain.find_by(name: pair[0]).nil?
      Common::Strain.create!({
        name: pair[0],
        strain_type: pair[1]
      })
      puts "Created strain: #{pair[0]}"
    end
  end
end