strains = [
  ['$100 OG','Hybrid'],
  ['9 Pound Hammer','Indica'],
  ['Acapulco Gold','Sativa'],
  ['ACDC','Hybrid'],
  ['Afghani','Indica'],
  ['Afgoo','Indica'],
  ['AK-47','Hybrid'],
  ['Alaskan Thunder Fuck','Sativa'],
  ['Allen Wrench','Sativa'],
  ['Amnesia','Sativa'],
  ['Amnesia Haze','Sativa'],
  ['Banana OG','Hybrid'],
  ['Bay 11','Sativa'],
  ['Berry White','Indica'],
  ['Blackberry Kush','Indica'],
  ['Blue Cheese','Indica'],
  ['Blue Dream','Hybrid'],
  ['Blueberry','Indica'],
  ['Bubba Kush','Indica'],
  ['Bubble Gum','Hybrid'],
  ['Cannatonic','Hybrid'],
  ['Cheese','Hybrid'],
  ['ChemDawg','Hybrid'],
  ['Chernobyl','Hybrid'],
  ['Cherry Pie','Hybrid'],
  ['Chocolope','Sativa'],
  ['Cinderella 99','Hybrid'],
  ['Cinex','Sativa'],
  ['Dancehall','Hybrid'],
  ['Death Star','Indica'],
  ['Dirty Girl','Sativa'],
  ['Double Dream','Hybrid'],
  ['Durban Poison','Sativa'],
  ['Dutch Treat','Hybrid'],
  ['Ewok','Hybrid'],
  ['Fruity Pebbles','Hybrid'],
  ['G13','Indica'],
  ['Gelato','Hybrid'],
  ['Ghost Train Haze','Sativa'],
  ['God’s Gift','Indica'],
  ['Golden Goat','Hybrid'],
  ['Granddaddy Purple','Indica'],
  ['Grape Ape','Indica'],
  ['Grapefruit','Sativa'],
  ['Green Crack','Sativa'],
  ['Harlequin','Sativa'],
  ['Headband','Hybrid'],
  ['Herijuana','Indica'],
  ['Hindu Kush','Indica'],
  ['Ingrid','Indica'],
  ['Island Sweet Skunk','Sativa'],
  ['Jack Herer','Sativa'],
  ['Jean Guy','Hybrid'],
  ['Jilly Bean','Hybrid'],
  ['Juicy Fruit','Hybrid'],
  ['Kali Mist','Sativa'],
  ['Kosher Kush','Indica'],
  ['LA Confidential','Indica'],
  ['Lamb\'s Bread','Sativa'],
  ['Larry OG','Hybrid'],
  ['Laughing Buddha','Sativa'],
  ['Lavender','Indica'],
  ['Lemon Haze','Sativa'],
  ['Lemonder','Hybrid'],
  ['Lodi Dodi','Hybrid'],
  ['Mango Kush','Hybrid'],
  ['Master Kush','Indica'],
  ['Maui Wowie','Sativa'],
  ['Mendicino Purps','Hybrid'],
  ['Middle Fork','Hybrid'],
  ['Northern Lights','Indica'],
  ['Obama Kush','Indica'],
  ['OG Kush','Hybrid'],
  ['Panama red','Sativa'],
  ['Permafrost','Hybrid'],
  ['Pez','Indica'],
  ['Pineapple Chunk','Hybrid'],
  ['Pineapple Express','Hybrid'],
  ['Pink Kush','Hybrid'],
  ['Plushberry','Indica'],
  ['Presidential OG','Indica'],
  ['Purple Haze','Sativa'],
  ['Purple Kush','Indica'],
  ['Purple Urkle','Indica'],
  ['Rascal OG','Hybrid'],
  ['Red Headed Stranger','Sativa'],
  ['S.A.G.E.','Hybrid'],
  ['Schrom','Sativa'],
  ['SFG OG','Hybrid'],
  ['Shiatsu Kush','Hybrid'],
  ['Skunk #1','Hybrid'],
  ['Skywalker','Indica'],
  ['Skywalker OG','Hybrid'],
  ['Snoop\'s Dream','Hybrid'],
  ['Snowcap','Hybrid'],
  ['Sour Diesel','Sativa'],
  ['Sour OG','Hybrid'],
  ['Sour Tsunami','Hybrid'],
  ['Space Queen','Hybrid'],
  ['Strawberry Cough','Sativa'],
  ['Sunset Sherbet','Hybrid'],
  ['Super Lemon Haze','Sativa'],
  ['Super Silver Haze','Sativa'],
  ['Tahoe OG','Hybrid'],
  ['Tangerine Dream','Hybrid'],
  ['Tangie','Sativa'],
  ['Trainwreck','Hybrid'],
  ['UK Cheese','Hybrid'],
  ['White Fire OG','Hybrid'],
  ['White Rhino','Indica'],
  ['White Widow','Hybrid'],
  ['Willie\'s Wonder','Indica'],
  ['XJ-13','Hybrid'],
  ['Zkittles','Indica']
]


desc "Seed popular strains"
task seed_strain: :environment  do
  strains.each do |pair|
    code = pair[0].gsub(/[\'\s]/, '').underscore

    if Common::Strain.find_by(name: pair[0]).nil?
      Common::Strain.create!({
        name: pair[0],
        strain_type: pair[1]
      })
      puts "Created strain: #{pair[0]}"
    end
  end
end