batch_activation_job:
  cron: "0 * * * *" #run worker every one hour
  class: "ActivateBatchWorker"
  queue: "low"
system_notification_job:
  cron: "0 0 * * *" # run worker every hours
  class: "DailySystemNotificationWorker"
  queue: "low"
update_worker_arrival_job:
  cron: "*/15 * * * *" # run worker every 15 minutes
  class: "UpdateWorkerArrivalStatusWorker"
  queue: "low"