batch_activation_job:
  cron: "*/15 * * * *" # run worker every 15 minutes
  class: "ActivateBatchWorker"
  queue: "low"
system_notification_job:
  cron: "*/1 * * * *" # run worker every hours
  class: "DailySystemNotificationWorker"
  queue: "low"
