class Row
  include Mongoid::Document

  field :name, type: String
  field :code, type: String
  field :is_complete, type: Boolean, default: -> { false }
  # indicate record was generated by wizard
  # set to false after user saved
  field :wz_generated, type: Boolean, default: -> { true }

  embedded_in :room
  embeds_many :shelves, class_name: 'Shelf'
end
